### Pytorch Tensors

In [2]:
import torch

In [3]:
a = torch.ones(3);a

tensor([1., 1., 1.])

In [9]:
a[1:3]

tensor([1., 1.])

In [10]:
float(a[1])

1.0

In [5]:
a[2]=2.0;a

tensor([1., 1., 2.])

In [11]:
x = torch.tensor([1.0,2.0,3.0,4.0])
x

tensor([1., 2., 3., 4.])

In [12]:
x = torch.tensor([[1.0,2.0],[4.0,5.0],[6.0,7.0]])
print(x.shape)
x

torch.Size([3, 2])


tensor([[1., 2.],
        [4., 5.],
        [6., 7.]])

In [13]:
x = torch.zeros(3,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
x = torch.FloatTensor([[1.,2.,3.],[3.,4.,5.]])
x.shape

torch.Size([2, 3])

In [15]:
x[1,1]

tensor(4.)

In [16]:
x[0],x[0].shape

(tensor([1., 2., 3.]), torch.Size([3]))

In [17]:
x.storage()

 1.0
 2.0
 3.0
 3.0
 4.0
 5.0
[torch.FloatStorage of size 6]

In [18]:
x.storage()[2]

3.0

In [19]:
x.storage()[2] = 7.0
x

tensor([[1., 2., 7.],
        [3., 4., 5.]])

In [27]:
x = torch.tensor([[1.0, 4.0, 6.0], [2.0, 1.0, 4.0], [3.0, 5.0, 2.0]])
y = x[1]
print(y,y.size(),y.shape)
y.storage_offset()

tensor([2., 1., 4.]) torch.Size([3]) torch.Size([3])


3

In [28]:
x.storage()

 1.0
 4.0
 6.0
 2.0
 1.0
 4.0
 3.0
 5.0
 2.0
[torch.FloatStorage of size 9]

In [29]:
x.stride()

(3, 1)

In [30]:
y.stride()

(1,)

In [32]:
x.t()

tensor([[1., 2., 3.],
        [4., 1., 5.],
        [6., 4., 2.]])

In [33]:
x.t().stride()

(1, 3)

In [34]:
id(x.storage()) == id(x.t().storage())

True

In [36]:
double_x = torch.ones(3, 2, dtype=torch.double)
short_x = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [37]:
print(double_x)
short_x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [38]:
short_x.dtype

torch.int16

In [40]:
a = x.numpy();a

array([[1., 4., 6.],
       [2., 1., 4.],
       [3., 5., 2.]], dtype=float32)

In [43]:
A = torch.from_numpy(a);A

tensor([[1., 4., 6.],
        [2., 1., 4.],
        [3., 5., 2.]])

In [44]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
print(img_t.size())
img_t

torch.Size([3, 5, 5])


tensor([[[ 0.6136, -0.0728, -0.7937,  0.6350, -0.7502],
         [ 1.6061,  1.5373, -0.4023,  0.4143,  0.4382],
         [ 0.6198,  0.8629,  0.9735,  1.9583, -1.3002],
         [ 1.2957, -0.5031,  0.3791, -1.0966,  0.4626],
         [ 0.6835,  1.3504,  0.7047, -0.4361, -0.3830]],

        [[-0.4627,  1.6454,  0.1079,  0.6100, -0.7876],
         [ 1.0493, -0.3982, -1.2213, -0.8720,  0.1577],
         [ 0.5980,  0.2103, -1.2648,  0.4820,  1.8069],
         [ 1.5793,  0.6436, -0.6144,  0.1425, -1.2049],
         [-0.8927,  0.8846, -0.1988,  0.9600, -0.9848]],

        [[-0.1753, -1.2172,  0.4777, -0.2732,  0.2662],
         [-1.3945,  0.2930, -1.6944,  0.6989,  0.5107],
         [ 1.8822,  0.4689,  0.1104,  0.5032, -0.0685],
         [-0.9265,  1.2213, -1.0363, -2.3298, -2.1669],
         [ 0.6947, -0.8521, -0.6626, -2.2948, -0.4728]]])

In [45]:
img_t[:,0,0]

tensor([ 0.6136, -0.4627, -0.1753])

In [46]:
img_t[:,1,:]

tensor([[ 1.6061,  1.5373, -0.4023,  0.4143,  0.4382],
        [ 1.0493, -0.3982, -1.2213, -0.8720,  0.1577],
        [-1.3945,  0.2930, -1.6944,  0.6989,  0.5107]])

In [47]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[-0.9493,  0.4486,  1.8783,  0.4737,  1.3754],
          [-1.2231, -0.6425, -0.8296, -1.3454,  1.0959],
          [-0.0534,  0.2097,  0.8660, -0.6386,  0.3880],
          [ 0.4152, -2.4382,  0.8215, -0.0477, -0.2980],
          [-0.1805, -1.1153,  0.6218, -0.5755,  0.1887]],

         [[-0.7509, -0.3024,  0.7690,  0.4211, -1.7331],
          [-0.1278, -2.4005, -0.2341,  0.2700, -0.7228],
          [-0.6395, -0.4257, -0.4924, -2.1536, -0.1976],
          [-1.9727,  1.0771,  1.6743, -0.4231,  0.0527],
          [-1.5350, -0.1913,  0.0841, -1.9005,  0.4010]],

         [[-0.8498, -0.9244,  0.6567, -0.3928,  0.1377],
          [ 2.5532,  0.4565, -1.2087,  0.2961, -0.8140],
          [ 0.4442,  3.1709,  0.5381, -2.3033, -0.4468],
          [ 0.3332, -0.0864, -0.8792,  0.5194,  0.4371],
          [-1.1237, -0.2513,  0.5954, -0.1077,  0.1256]]],


        [[[-0.6185,  0.4853, -0.2069, -1.5930,  0.2517],
          [-0.2672,  0.8161,  0.6983,  0.7086,  0.2586],
          [-0.2009,  0.

In [50]:
print(img_t.shape)
print(img_t.mean(-3))
img_t.mean(dim=0)

torch.Size([3, 5, 5])
tensor([[-0.0081,  0.1185, -0.0693,  0.3239, -0.4238],
        [ 0.4203,  0.4774, -1.1060,  0.0804,  0.3689],
        [ 1.0333,  0.5140, -0.0603,  0.9811,  0.1461],
        [ 0.6495,  0.4539, -0.4238, -1.0947, -0.9697],
        [ 0.1618,  0.4609, -0.0522, -0.5903, -0.6135]])


tensor([[-0.0081,  0.1185, -0.0693,  0.3239, -0.4238],
        [ 0.4203,  0.4774, -1.1060,  0.0804,  0.3689],
        [ 1.0333,  0.5140, -0.0603,  0.9811,  0.1461],
        [ 0.6495,  0.4539, -0.4238, -1.0947, -0.9697],
        [ 0.1618,  0.4609, -0.0522, -0.5903, -0.6135]])

In [55]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

weights.shape,unsqueezed_weights.shape

(torch.Size([3]), torch.Size([3, 1, 1]))

In [56]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [58]:
print(img_t.shape,unsqueezed_weights.shape)
img_weights = (img_t * unsqueezed_weights)
img_weights.shape

torch.Size([3, 5, 5]) torch.Size([3, 1, 1])


torch.Size([3, 5, 5])

In [59]:
print(batch_t.shape,unsqueezed_weights.shape)
batch_weights = (batch_t * unsqueezed_weights) 
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3) 
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

torch.Size([2, 3, 5, 5]) torch.Size([3, 1, 1])


(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
print(points)
second_point

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


tensor([10.,  3.])

In [17]:
def func(x):
    return (x**3 - 7*x**2 + 11*x)

In [18]:
func(3)

-3

In [19]:
x = torch.tensor(3.0,requires_grad=True)

In [20]:
y=func(x)

In [21]:
type(y)

torch.Tensor

In [22]:
y

tensor(-3., grad_fn=<AddBackward0>)

In [23]:
x

tensor(3., requires_grad=True)

In [24]:
y.backward()

In [25]:
x.grad

tensor(-4.)

In [27]:
u=torch.tensor(2.0,requires_grad=True)
v=torch.tensor(1.0,requires_grad=True)

In [28]:
f=3*u**2*v - 4*v**3

In [29]:
f

tensor(8., grad_fn=<SubBackward0>)

In [30]:
f.backward(retain_graph=True)

In [31]:
u.grad,v.grad

(tensor(12.), tensor(0.))

In [60]:
x=torch.linspace(-10.0,10.0,10,requires_grad=True)

In [61]:
x

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000], requires_grad=True)

In [62]:
x_squared=x**2

In [63]:
x_squared

tensor([100.0000,  60.4938,  30.8642,  11.1111,   1.2346,   1.2346,  11.1111,
         30.8642,  60.4938, 100.0000], grad_fn=<PowBackward0>)

In [43]:
y=torch.sum(x_squared)

In [44]:
y

tensor(3400.6733, grad_fn=<SumBackward0>)

In [10]:
x = torch.randn(3,requires_grad=True)
print(x)

y = x+2
print(y)
z = y*y*2
z = z.mean() #scaler
print(z)

z.backward()
print(z)
print(x.grad)

tensor([1.5581, 0.8244, 0.9309], requires_grad=True)
tensor([3.5581, 2.8244, 2.9309], grad_fn=<AddBackward0>)
tensor(19.4851, grad_fn=<MeanBackward0>)
tensor(19.4851, grad_fn=<MeanBackward0>)
tensor([4.7441, 3.7659, 3.9079])


In [11]:
x = torch.randn(3,requires_grad=True)
print(x)

y = x+2
print(y)
z = y*y*2
print(z)

v = torch.tensor([0.1, 1.0,0.001],dtype=torch.float32)
z.backward(v)
print(z)

tensor([0.8311, 0.3304, 0.5485], requires_grad=True)
tensor([2.8311, 2.3304, 2.5485], grad_fn=<AddBackward0>)
tensor([16.0307, 10.8616, 12.9899], grad_fn=<MulBackward0>)
tensor([16.0307, 10.8616, 12.9899], grad_fn=<MulBackward0>)


In [4]:
weights = torch.ones(4,requires_grad=True)
x = 3
for epoch in range(3):
    model_output = (weights*x).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


https://www.kdnuggets.com/2020/06/fundamentals-pytorch.html

## TensorFlow tensors

In [64]:
import tensorflow as tf

tf.random.set_seed(42)
tf.__version__

'2.1.0'

In [7]:
x = tf.constant(1);x

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
x.numpy()

1

In [9]:
x.shape

TensorShape([])

In [10]:
m = tf.constant([[1, 2, 1], [3, 4, 2]]);m

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 1],
       [3, 4, 2]], dtype=int32)>

In [11]:
m.shape

TensorShape([2, 3])

In [12]:
ones = tf.ones([3, 3])
ones

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
zeros = tf.zeros([2, 3])
print(zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [14]:
tf.reshape(zeros, [3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [15]:
tf.transpose(zeros)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
a = tf.constant(1)
b = tf.constant(1)

tf.add(a, b).numpy()

2

In [17]:
(a + b).numpy()

2

In [18]:
c = a + b
c * c

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [19]:
d1 = tf.constant([[1, 2], [1, 2]]);
d2 = tf.constant([[3, 4], [3, 4]]);

tf.tensordot(d1, d2, axes=1).numpy()

array([[ 9, 12],
       [ 9, 12]], dtype=int32)

In [20]:
norm = tf.random.normal(shape=(1000, 1), mean=0., stddev=1.)

In [21]:
unif = tf.random.uniform(shape=(1000, 1), minval=0, maxval=100)